<?php

##
## Configuration du texte français

$LANG = array
(

// Données de la page /livre_d-or/admin/index.php
'ENTETE_titre' 						=> "Connexion",
'FORMULAIRE_titre' 					=> "Connexion à l'administration",
'FORMULAIRE_pseudo' 				=> "Pseudo",
'FORMULAIRE_pass' 					=> "Mot de passe",
'FORMULAIRE_erreur_pseudo' 			=> "Le pseudo saisi est incorrecte",
'FORMULAIRE_erreur_pass' 			=> "Le mot de passe saisi est incorrecte",
'FORMULAIRE_bouton' 				=> "Connexion",
'LIEN_retour' 						=> "Retour",

// Données de la page /livre_d-or/admin/administration.php
'ADMIN_entete_titre' 				=> "Configuration du livre d'or",
'ADMIN_erreur_champ' 				=> "La partie « Configuration du livre d'or » et le champ « Nom d'utilisateur » sont obligatoires",
'ADMIN_erreur_pass' 				=> "La vérification du mot de passe a échoué",
'ADMIN_ok' 							=> "Les données ont été mise à jour",
'ADMIN_maj' 						=> "[strong]Nouvelle version du script disponible[/strong][br][br]Vous utilisez la version [version], la dernière version du script est la [derniere_version][br]La version [derniere_version] est à télécharger sur le [site]site officiel[/site] du script ![br][br]",
'FORMULAIRE_ident_titre' 			=> "Identifiants de l'administration",
'FORMULAIRE_ident_user' 			=> "Nom d'utilisateur",
'FORMULAIRE_ident_pass' 			=> "Mot de passe",
'FORMULAIRE_ident_pass_verif' 		=> "Retapez votre mot de passe",
'FORMULAIRE_config_titre' 			=> "Configuration du livre d'or *",
'FORMULAIRE_config_separateur' 		=> "Separateur de message (utilisateur/webmaster)",
'FORMULAIRE_config_nb_message' 		=> "Nombre maximal de message affiché par page",
'FORMULAIRE_config_db_titre' 		=> "Titre du livre d'or",
'FORMULAIRE_config_flood' 			=> "Autoriser le flood ?",
'FORMULAIRE_config_flood_infos' 	=> "Configuration des doubles postes",
'FORMULAIRE_config_flood_option_1' 	=> "Ne jamais l'autoriser",
'FORMULAIRE_config_flood_option_2' 	=> "Toujours l'autoriser",
'FORMULAIRE_config_flood_option_3' 	=> "Autoriser uniquement en cas de réponse du webmaster",
'FORMULAIRE_config_br' 				=> "Prendre en compte les sauts de ligne ?",
'FORMULAIRE_config_br_infos' 		=> "Configuration utilisateurs/webmaster",
'FORMULAIRE_config_br_option_1' 	=> "Uniquement pour les réponses du webmaster",
'FORMULAIRE_config_br_option_2' 	=> "Pour les messages des utilisateurs et du webmaster",
'FORMULAIRE_config_oui' 			=> "Oui",
'FORMULAIRE_config_non' 			=> "Non",
'FORMULAIRE_config_msg_titre' 		=> "Message d'en-tête",
'FORMULAIRE_config_msg' 			=> "Votre message d'en-tête",
'FORMULAIRE_condition' 				=> "La partie « Configuration du livre d'or » et le champ « Nom d'utilisateur »<br />sont obligatoires",
'FORMULAIRE_config_bouton' 			=> "Mettre à jour",
'FORMULAIRE_anti_bot_titre' 		=> "Configuration de l'anti-robot *",
'FORMULAIRE_anti_bot_infos' 		=> "Captcha",
'FORMULAIRE_anti_bot_choix_1' 		=> "Reconnaissance par image - Efficacité bonne",
'FORMULAIRE_anti_bot_choix_2' 		=> "Reconnaissance par copie - Efficacité moyenne",
'FORMULAIRE_anti_bot_choix_3' 		=> "Reconnaissance par calcul - Efficacité faible",
'FORMULAIRE_plus' 					=> "Agrandir la taille du formulaire",
'FORMULAIRE_moins'	 				=> "Réduire la taille du formulaire",

// Données de la page /livre_d-or/admin/administration_design.php
'ADMIN_design_entete_titre' 		=> "Configuration du graphique",
'ADMIN_design_champ_pasok' 			=> "Tous les champs sont obligatoires",
'ADMIN_design_css_ok' 				=> "Le graphique a été mise à jour",
'ADMIN_design_css_pasok' 			=> "Impossible d'écrire le fichier (vérifiez que le CHMOD 777 a bien été appliqué au fichier « style.css »)",
'ADMIN_design_lien_palette' 		=> "Afficher la palette de couleurs",
'ADMIN_design_titre_palette' 		=> "Palette de couleurs",
'ADMIN_design_infos_palette' 		=> "Cliquez sur une couleur pour bloquer/débloquer la selection",
'ADMIN_design_from_corp_titre' 		=> "Corp du graphique",
'ADMIN_design_from_corp_c_text_i' 	=> "Couleur du texte",
'ADMIN_design_from_corp_c_fond_i' 	=> "Couleur de fond intérieur",
'ADMIN_design_from_corp_c_border_e'	=> "Couleur de la bordure (Inutil si intégré)", // *
'ADMIN_design_from_corp_c_fond_e' 	=> "Couleur de fond extérieur (Inutil si intégré)", // *
'ADMIN_design_from_head_titre'		=> "Configuration de l'en-tête",
'ADMIN_design_from_head_i_titre'	=> "Titre du livre d'or",
'ADMIN_design_from_head_tail_titre'	=> "Taille du titre",
'ADMIN_design_from_head_c_titre'	=> "Couleur du titre",
'ADMIN_design_from_head_i_msg'		=> "Message d'en-tête",
'ADMIN_design_from_head_tail_msg'	=> "Taille du texte",
'ADMIN_design_from_head_c_msg'		=> "Couleur du texte",
'ADMIN_design_from_head_align_msg'	=> "Alignement du texte",
'ADMIN_design_from_head_align_msg_c'=> "Centrer",
'ADMIN_design_from_head_align_msg_l'=> "Gauche",
'ADMIN_design_from_head_align_msg_r'=> "Droite",
'ADMIN_design_from_head_align_msg_j'=> "Justifier",
'ADMIN_design_from_head_i_reste'	=> "Le reste",
'ADMIN_design_from_taille_nb_msg'	=> "Taille du texte affichant le nombre de message",
'ADMIN_design_from_taille_moyen_msg'=> "Taille du texte affichant la moyenne du site",
'ADMIN_design_from_f_titre'			=> "Configuration du formulaire",
'ADMIN_design_from_f_i_encadre'		=> "Encadrement du formulaire",
'ADMIN_design_from_f_width_encadre'	=> "Largeur de l'encadrement",
'ADMIN_design_from_f_border_encadre'=> "Couleur de la bordure",
'ADMIN_design_from_f_i_titre'		=> "Titre du formulaire",
'ADMIN_design_from_f_c_titre'		=> "Couleur du titre",
'ADMIN_design_from_f_fond_titre'	=> "Couleur de fond du titre",
'ADMIN_design_from_msg_titre'		=> "Configuration des messages",
'ADMIN_design_from_msg_cf_entete'	=> "Couleur de fond de l'en-tête",
'ADMIN_design_from_msg_cf_msg'		=> "Couleur de fond des message",
'ADMIN_design_from_msg_cf_pied'		=> "Couleur de fond du pied",
'ADMIN_design_from_msg_c_webmast'	=> "Couleur du texte des messages webmaster",
'ADMIN_design_from_msg_cb_encadre'	=> "Couleur de la bordure de l'encadrement",
'ADMIN_design_from_msg_w_encadre'	=> "Largeur de l'encadrement des messages",
'ADMIN_design_from_lien_titre'		=> "Configuration des liens",
'ADMIN_design_from_lien_c'			=> "Couleur du lien",
'ADMIN_design_from_lien_cf'			=> "Couleur de fond du lien",
'ADMIN_design_from_lien_infos'		=> "Liens non survolés par la souris",
'ADMIN_design_from_lien_infos2'		=> "Liens survolés par la souris",
'ADMIN_design_from_lien_hover_c'	=> "Couleur du lien",
'ADMIN_design_from_lien_hover_cf'	=> "Couleur de fond du lien",
'ADMIN_design_from_condition'		=> "Tous les champs sont obligatoires",
'ADMIN_design_from_bouton'			=> "Mettre à jour",

// Données de la page /livre_d-or/admin/menu.php
'MENU_config' 						=> "Configuration du livre d'or",
'MENU_design' 						=> "Configuration graphique",
'MENU_gestion' 						=> "Gestion des messages",
'MENU_deco' 						=> "Déconnexion",

// Données de la page /livre_d-or/admin/administration_message.php
'ADMIN_msg_entete_titre' 			=> "Administration des messages",
'ADMIN_msg_suppr_ok'	 			=> "Le message a bien été supprimé",
'ADMIN_msg_nb_aucun'	 			=> "Il n'y a pas encore de message dans le livre d'or",
'ADMIN_msg_nb_singulier'	 		=> "Il y a actuellement <strong>1</strong> message dans le livre d'or",
'ADMIN_msg_nb_pluriel'	 			=> "Il y a actuellement <strong>". @$nb_msg ."</strong> messages dans le livre d'or",
'ADMIN_msg_moeyenne'	 			=> "Moyenne du site ",
'ADMIN_msg_page_suivante'	 		=> "Page suivante",
'ADMIN_msg_page_precedente'	 		=> "Page précédente",

// Données de la page /livre_d-or/admin/message.php
'ADMIN_msg_alt_enveloppe' 			=> "Email du posteur",
'ADMIN_msg_alt_maison' 				=> "Email du posteur",
'ADMIN_msg_msg_note' 				=> "Note : ",
'ADMIN_msg_msg_no_note' 			=> "Non évalué",
'ADMIN_msg_suppr' 					=> "Supprimer le message",
'ADMIN_msg_suppr_verif' 			=> "Etes-vous sur de vouloir supprimer ce message ?",
'ADMIN_msg_suppr_oui' 				=> "Oui",
'ADMIN_msg_suppr_non' 				=> "Non",
'ADMIN_msg_edit' 					=> "Editer le message",
'ADMIN_msg_edit_form_pseudo' 		=> "Pseudo *",
'ADMIN_msg_edit_form_email' 		=> "Email",
'ADMIN_msg_edit_form_ville' 		=> "Ville",
'ADMIN_msg_edit_form_pays' 			=> "Pays",
'ADMIN_msg_edit_form_url' 			=> "Site internet",
'ADMIN_msg_edit_form_note' 			=> "Note donnée au site",
'ADMIN_msg_edit_form_msg' 			=> "Message *",
'ADMIN_msg_edit_form_condition' 	=> "Les champs « Pseudo » et « Message » sont obligatoires",
'ADMIN_msg_edit_form_bouton' 		=> "Modifier",
'ADMIN_msg_edit_form_pas_ok' 		=> "Les champs « Pseudo » et « Message » sont obligatoires",
'ADMIN_msg_edit_form_ok' 			=> "Le message a bien été mise à jour",
'ADMIN_msg_repondre' 				=> "Répondre/modifier la réponse",
'ADMIN_msg_repondre_form_reponse' 	=> "Votre réponse",
'ADMIN_msg_repondre_form_bouton' 	=> "Répondre/Modifier",
'ADMIN_msg_repondre_form_ok' 		=> "La mise à jour a bien été effectuée",

// Données de la page /livre_d-or/admin/deconnexion.php
'DECO_entete_titre' 				=> "Déconnexion",
'DECO_ok' 							=> "Vous avez été correctement déconnecté",
'DECO_lien_retour' 					=> "Retour au livre d'or"

);

?>